# Shekere Example Playlist

[midi.navigation.next]
cc = 21

[midi.navigation.prev]
cc = 20

[osc.navigation.next]
key = "s"
value = "bd"

[osc.navigation.prev]
key = "s"
value = "cp"

[[sketch]]
file = "shader_stars.js"
midi_note = 48 # C2

[[sketch]]
file = "audio_reactive_knot.js"
midi_note = 49 # C#2

[[sketch]]
file = "midi_reactive.js"
midi_note = 50 # D2

[[sketch]]
file = "spectrum.js"
midi_note = 51 # D#2

[[sketch]]
file = "effects_showcase.js"
midi_note = 52 # E2

[[sketch]]
file = "tidal_reactive.js"
osc_key = "s"
osc_value = "sd"

[[sketch]]
file = "hello_world.js"
osc_key = "s"
osc_value = "hc"