[window]
width = 1200
height = 800

[[pipeline]]
shader_type = "fragment"
label = "Spectrum History Fragment Shader"
entry_point = "fs_main"
file = "fragment.wgsl"

[spectrum]
min_frequency = 20.0
max_frequency = 8000.0
sampling_rate = 44100

[hot_reload]
enabled = true