[window]
width = 800
height = 800

[[pipeline]]
shader_type = "fragment"
label = "Kaleidoscope Feedback"
entry_point = "fs_main"
file = "kaleidoscope.wgsl"
ping_pong = true

[hot_reload]
enabled = true